# Base Image
FROM python:3.12.4-slim-bookworm

# Set working directory
WORKDIR /app

# Install supervisor
RUN apt-get update && apt-get install -y supervisor

# Copy necessary files
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install redis

# The base image does not define a CMD or ENTRYPOINT
# It will be defined in the final image Dockerfile
