"""empty message

Revision ID: 8929a1afeddb
Revises: e5639b1cfd99
Create Date: 2024-08-12 16:02:28.640908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8929a1afeddb'
down_revision = 'e5639b1cfd99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ag_autorun_result', schema=None) as batch_op:
        batch_op.alter_column('autorun_func',
               existing_type=postgresql.ENUM('updateJeusDomain', 'updateHttpm', 'updateWebMain', 'updateWasStatus', 'updateUrlRewrite', 'readOutFile', 'readCIDOutFile', 'updateConnectSSL', 'updateConnectSSLByAPI', 'update_file_SSL_byAPI', 'updateFileSSL', 'restartMWAgent', 'updateJeusLicenseInfo', 'updateWebtobLicenseInfo', 'updateJeusProperties', 'updateWebtobVersion', 'updateWebtobMonitor', 'updateFilteredInfo', name='autorunfuncenum'),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('ag_command_master', schema=None) as batch_op:
        batch_op.alter_column('interval_type',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('minutes', 'hours', 'days', name='intervaltypeenum'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ag_command_master', schema=None) as batch_op:
        batch_op.alter_column('interval_type',
               existing_type=sa.Enum('minutes', 'hours', 'days', name='intervaltypeenum'),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)

    with op.batch_alter_table('ag_autorun_result', schema=None) as batch_op:
        batch_op.alter_column('autorun_func',
               existing_type=sa.String(length=100),
               type_=postgresql.ENUM('updateJeusDomain', 'updateHttpm', 'updateWebMain', 'updateWasStatus', 'updateUrlRewrite', 'readOutFile', 'readCIDOutFile', 'updateConnectSSL', 'updateConnectSSLByAPI', 'update_file_SSL_byAPI', 'updateFileSSL', 'restartMWAgent', 'updateJeusLicenseInfo', 'updateWebtobLicenseInfo', 'updateJeusProperties', 'updateWebtobVersion', 'updateWebtobMonitor', 'updateFilteredInfo', name='autorunfuncenum'),
               existing_nullable=False)

    # ### end Alembic commands ###
