"""empty message

Revision ID: e5639b1cfd99
Revises: 1f22dabe20a9
Create Date: 2024-08-08 14:36:31.069989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5639b1cfd99'
down_revision = '1f22dabe20a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ag_command_master', schema=None) as batch_op:
        batch_op.alter_column('interval_type',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('minutes', 'hours', 'days', name='intervaltypeenum'),
               existing_nullable=True)

    with op.batch_alter_table('mw_was', schema=None) as batch_op:
        batch_op.alter_column('was_text',
               existing_type=sa.TEXT(),
               comment='WAS 정보',
               existing_comment='변경전 WAS 정보',
               existing_nullable=True)

    with op.batch_alter_table('mw_web', schema=None) as batch_op:
        batch_op.add_column(sa.Column('web_text', sa.Text(), nullable=True, comment='WEB 정보'))

    with op.batch_alter_table('mw_web_change_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_web_text', sa.Text(), nullable=True, comment='변경전 WEB 정보'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mw_web_change_history', schema=None) as batch_op:
        batch_op.drop_column('old_web_text')

    with op.batch_alter_table('mw_web', schema=None) as batch_op:
        batch_op.drop_column('web_text')

    with op.batch_alter_table('mw_was', schema=None) as batch_op:
        batch_op.alter_column('was_text',
               existing_type=sa.TEXT(),
               comment='변경전 WAS 정보',
               existing_comment='WAS 정보',
               existing_nullable=True)

    with op.batch_alter_table('ag_command_master', schema=None) as batch_op:
        batch_op.alter_column('interval_type',
               existing_type=sa.Enum('minutes', 'hours', 'days', name='intervaltypeenum'),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
